export const CUISINE_LABELS = {
  yunnan: "云南",
  hunan: "湘菜",
  korean: "韩国街",
  western: "西餐",
  hotpot: "火锅",
  seafood: "海鲜",
  thai: "泰国菜",
  nepalese: "尼泊尔菜",
  chaoshan: "潮汕牛肉锅",
  dessert: "甜品",
  sichuan: "川菜",
  northeast: "东北菜",
};

export const ROUTE_INTENT_LABELS = {
  easy: "公司附近省事",
  home_route: "回家顺路",
  worth_trip: "为了好吃专门去",
  city_walk: "进城吃完逛",
  any: "路线都可以",
};

export const restaurants = [
  {
    id: "tiao-he",
    name: "跳河大排档",
    address: "育婴堂路117号永兴汇6栋1层A室",
    location: {
      bucket: "middle_distance_destination",
      label: "育婴堂路永兴汇",
      driveCompany: "中距离",
      driveHome: "中等",
      transitCompany: "偏折腾",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "为了吃才值得",
      afterMealOptions: ["专门去"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "top",
      isChain: false,
      mealScale: "big",
      familiar: true,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "yunnan_spicy",
      heaviness: "medium",
    },
    dishes: [
      "藿香脆鳝鱼",
      "避风塘基围虾",
      "酸汤石斑鱼",
      "牛蛙酸笋爆炒",
    ],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["想吃云南 top", "愿意中距离专门去", "想吃酸辣大菜"],
      avoidWhen: ["云南熟脸腻了", "不想专门跑"],
      vetoRisks: ["专门去", "熟脸"],
    },
  },
  {
    id: "yun-zhi-yun-wei",
    name: "云汁云味",
    address: "崇溪路111弄62号",
    location: {
      bucket: "middle_distance_destination",
      label: "崇溪路",
      driveCompany: "30min",
      driveHome: "很痛苦",
      transitCompany: "中等",
      transitHome: "很痛苦",
      detour: "major_detour",
      routeVerdict: "为了吃才值得",
      afterMealOptions: ["专门去"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "top",
      isChain: false,
      mealScale: "big",
      familiar: true,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "yunnan_spicy",
      heaviness: "medium",
    },
    dishes: ["小锅米线", "油炝心管", "烤猪皮", "傣味舂鸡脚", "傣味佐料炒牛肉", "烤粉肠"],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["云南 top", "很想吃才去"],
      avoidWhen: ["不想折腾", "熟脸腻了"],
      vetoRisks: ["回家很痛苦", "熟脸"],
    },
  },
  {
    id: "guo-wan-piao-xiang",
    name: "锅碗飘湘",
    address: "长宁路88号kiNG88广场负一层",
    location: {
      bucket: "middle_distance_destination",
      label: "长宁路 KiNG88",
      driveCompany: "中距离",
      driveHome: "中等",
      transitCompany: "中等",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "为了吃才值得",
      afterMealOptions: ["专门去"],
    },
    identity: {
      cuisine: "湘菜",
      cuisineFamilies: ["hunan"],
      preferenceTier: "top",
      isChain: false,
      mealScale: "big",
      familiar: true,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "hunan_hot",
      heaviness: "heavy",
    },
    dishes: ["拆骨肉炒荷包蛋", "长沙肉末烧米豆腐", "酸萝卜炒肥肠", "长沙地摊鸡蛋肉丝炒粉", "家常口味猪脚"],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["想吃很辣湘菜", "想吃下饭大菜"],
      avoidWhen: ["重口腻了", "熟脸腻了"],
      vetoRisks: ["重口", "熟脸"],
    },
  },
  {
    id: "yunnan-suan-tang-zhu-jiao",
    name: "云南酸汤猪脚",
    address: "中科路2428号1层",
    location: {
      bucket: "company_nearby",
      label: "中科路",
      driveCompany: "很近",
      driveHome: "中等",
      transitCompany: "很近",
      transitHome: "中等",
      detour: "small_detour",
      routeVerdict: "公司附近省事",
      afterMealOptions: ["早回", "省事"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "medium",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "sour_spicy",
      heaviness: "medium",
    },
    dishes: ["云南酸汤猪脚"],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["公司附近省事", "想吃酸汤"],
      avoidWhen: ["想出去逛", "想吃更大一顿"],
      vetoRisks: ["不够出门感"],
    },
  },
  {
    id: "he-liu-yuan",
    name: "和刘园云南餐厅",
    address: "淮海中路138号上海广场二楼205室",
    location: {
      bucket: "city",
      label: "淮海中路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["逛街"],
    },
    identity: {
      cuisine: "云南米线",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "low",
      isChain: false,
      mealScale: "small",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "yunnan_spicy",
      heaviness: "light",
    },
    dishes: ["小锅米线", "薄荷排骨", "果干米布", "包浆豆腐", "饵丝"],
    decision: {
      defaultEligibility: "usually_excluded",
      goodWhen: ["想吃云南小吃"],
      avoidWhen: ["要吃大的"],
      vetoRisks: ["小吃感"],
    },
  },
  {
    id: "dian-nan-yan-huo",
    name: "滇南烟火",
    address: "虹盛路227弄55-57号",
    location: {
      bucket: "middle_distance_destination",
      label: "虹盛路",
      driveCompany: "30min",
      driveHome: "很痛苦",
      transitCompany: "中等",
      transitHome: "很痛苦",
      detour: "major_detour",
      routeVerdict: "为了吃才值得",
      afterMealOptions: ["专门去"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "medium",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "yunnan_spicy",
      heaviness: "medium",
    },
    dishes: ["薄荷炸排骨", "文山黄牛肉串", "汆肉米线", "包浆豆腐", "烤粉肠"],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["想换云南菜", "不想熟脸 top"],
      avoidWhen: ["不想回家痛苦"],
      vetoRisks: ["回家很痛苦"],
    },
  },
  {
    id: "xi-dun",
    name: "玺炖中国铁锅炖",
    address: "祖冲之路1239弄长泰广场2座2楼24号铺",
    location: {
      bucket: "company_nearby",
      label: "长泰广场",
      driveCompany: "10min",
      driveHome: "中等",
      transitCompany: "很近",
      transitHome: "中等",
      detour: "small_detour",
      routeVerdict: "公司附近省事",
      afterMealOptions: ["早回", "省事"],
    },
    identity: {
      cuisine: "东北辣菜",
      cuisineFamilies: ["northeast"],
      preferenceTier: "exception",
      isChain: true,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "dry_spicy",
      heaviness: "heavy",
    },
    dishes: ["铁锅炖肋排"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["公司附近吃大的"],
      avoidWhen: ["不要连锁", "只想云南湘菜"],
      vetoRisks: ["连锁"],
    },
  },
  {
    id: "yu-ku",
    name: "鱼酷活鱼烤鱼",
    address: "祖冲之路1239弄长泰广场西区7座负一层05-3号",
    location: {
      bucket: "company_nearby",
      label: "长泰广场",
      driveCompany: "10min",
      driveHome: "中等",
      transitCompany: "很近",
      transitHome: "中等",
      detour: "small_detour",
      routeVerdict: "公司附近省事",
      afterMealOptions: ["早回", "省事"],
    },
    identity: {
      cuisine: "川菜",
      cuisineFamilies: ["sichuan"],
      preferenceTier: "exception",
      isChain: true,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "dry_spicy",
      heaviness: "heavy",
    },
    dishes: ["烤鱼"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["公司附近吃大的"],
      avoidWhen: ["不要连锁", "只想云南湘菜"],
      vetoRisks: ["连锁"],
    },
  },
  {
    id: "fen-ba",
    name: "粉八云南米线",
    address: "常熟路108弄前门4号",
    location: {
      bucket: "city",
      label: "常熟路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["喝酒", "逛街"],
    },
    identity: {
      cuisine: "云南米线",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "low",
      isChain: false,
      mealScale: "small",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "yunnan_spicy",
      heaviness: "light",
    },
    dishes: ["臭豆腐米线", "烧烤", "包浆豆腐", "羊肉米线"],
    decision: {
      defaultEligibility: "usually_excluded",
      goodWhen: ["想吃米线小吃"],
      avoidWhen: ["要吃大的"],
      vetoRisks: ["小吃感"],
    },
  },
  {
    id: "hunan-xiangcun",
    name: "湖南乡村风味馆",
    address: "乌鲁木齐中路168号",
    location: {
      bucket: "city",
      label: "乌鲁木齐中路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["逛街", "冰激凌"],
    },
    identity: {
      cuisine: "湘菜",
      cuisineFamilies: ["hunan"],
      preferenceTier: "medium",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "hunan_hot",
      heaviness: "heavy",
    },
    dishes: ["口味猪手", "干煸四季豆", "干锅芸豆", "姜辣紫苏焖牛蛙", "乡村辣子鸡", "酸豆角鸡肫"],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["不想锅碗但想湘菜", "进城可逛"],
      avoidWhen: ["别太重口"],
      vetoRisks: ["重口"],
    },
  },
  {
    id: "ma-chang",
    name: "马厂老火锅",
    address: "畹町路399号万科畹町坊停车场入口左侧",
    location: {
      bucket: "home_nearby",
      label: "家附近",
      driveCompany: "远",
      driveHome: "很顺",
      transitCompany: "远",
      transitHome: "很顺",
      detour: "on_the_way",
      routeVerdict: "回家顺路",
      afterMealOptions: ["家附近"],
    },
    identity: {
      cuisine: "火锅",
      cuisineFamilies: ["hotpot"],
      preferenceTier: "exception",
      isChain: true,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "hotpot_spicy",
      heaviness: "heavy",
    },
    dishes: ["辣火锅"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["想回家附近", "想吃火锅"],
      avoidWhen: ["不要连锁", "只想云南湘菜"],
      vetoRisks: ["连锁"],
    },
  },
  {
    id: "ban-shan-yao",
    name: "半山腰云南菜",
    address: "东育路500弄前滩太古里石区4楼S-L4-07商铺",
    location: {
      bucket: "middle_distance_destination",
      label: "前滩太古里",
      driveCompany: "中距离",
      driveHome: "中等",
      transitCompany: "中等",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "中距离可散步",
      afterMealOptions: ["散步", "奶茶"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "exception",
      isChain: true,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "medium",
      spiceStyle: "yunnan_spicy",
      heaviness: "medium",
    },
    dishes: ["母鸡炖菌汤", "黑松露酱炒饭", "油鸡纵酱烤饭", "牛扒烀"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["想去前滩散步", "云南但不重辣"],
      avoidWhen: ["不要连锁", "一定要很辣"],
      vetoRisks: ["连锁", "不够辣"],
    },
  },
  {
    id: "nan-man-zi-seafood",
    name: "南蛮子",
    address: "淮海中路1号美食不夜城2楼201",
    location: {
      bucket: "city",
      label: "淮海中路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步"],
    },
    identity: {
      cuisine: "海鲜",
      cuisineFamilies: ["seafood"],
      preferenceTier: "exception",
      isChain: true,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "none",
      spiceStyle: "not_spicy",
      heaviness: "medium",
    },
    dishes: ["海鲜"],
    decision: {
      defaultEligibility: "exception_pool",
      goodWhen: ["不想辣但要吃大的"],
      avoidWhen: ["要辣", "不要连锁"],
      vetoRisks: ["不辣", "连锁"],
    },
  },
  {
    id: "kaoroucun",
    name: "烤肉村多素拌韩国料理",
    address: "虹泉路1051弄35号1层乙室",
    location: {
      bucket: "korean_street",
      label: "韩国街",
      driveCompany: "中距离",
      driveHome: "顺路",
      transitCompany: "中等",
      transitHome: "顺路",
      detour: "small_detour",
      routeVerdict: "回家顺路",
      afterMealOptions: ["吃冰", "骑车回家"],
    },
    identity: {
      cuisine: "韩国菜",
      cuisineFamilies: ["korean"],
      preferenceTier: "top",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "medium",
      spiceStyle: "korean_spicy",
      heaviness: "medium",
    },
    dishes: ["辣味炖鸡锅"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["想韩国街", "吃完吃冰"],
      avoidWhen: ["只想云南湘菜", "一定要很辣"],
      vetoRisks: ["不够辣"],
    },
  },
  {
    id: "wang-zhuti",
    name: "王猪蹄艺拌",
    address: "虹泉路1000号井亭大厦B座1层109号",
    location: {
      bucket: "korean_street",
      label: "韩国街",
      driveCompany: "中距离",
      driveHome: "顺路",
      transitCompany: "中等",
      transitHome: "顺路",
      detour: "small_detour",
      routeVerdict: "回家顺路",
      afterMealOptions: ["吃冰", "骑车回家"],
    },
    identity: {
      cuisine: "韩国菜",
      cuisineFamilies: ["korean"],
      preferenceTier: "medium",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "medium",
      spiceStyle: "korean_spicy",
      heaviness: "medium",
    },
    dishes: ["王猪蹄"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["想韩国街", "回家顺路"],
      avoidWhen: ["只想云南湘菜", "一定要很辣"],
      vetoRisks: ["不够辣"],
    },
  },
  {
    id: "xiang-cui",
    name: "湘粹",
    address: "愚园东路20号SOHO东海广场4号楼1楼",
    location: {
      bucket: "city",
      label: "愚园东路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步"],
    },
    identity: {
      cuisine: "湘菜",
      cuisineFamilies: ["hunan"],
      preferenceTier: "low",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "hunan_hot",
      heaviness: "heavy",
    },
    dishes: ["爆炒牛蛙", "鸡脚筋", "口味猪手"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["湘菜低频", "进城散步"],
      avoidWhen: ["想稳妥 top"],
      vetoRisks: ["偏好低"],
    },
  },
  {
    id: "dou-pu-yuan",
    name: "豆濮园",
    address: "胶州路153号",
    location: {
      bucket: "city",
      label: "胶州路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步", "冰激凌", "喝酒"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "low",
      isChain: false,
      mealScale: "small",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "yunnan_spicy",
      heaviness: "light",
    },
    dishes: ["稀豆粉饵丝", "包浆豆腐", "五花肉蘸酸腌菜膏"],
    decision: {
      defaultEligibility: "usually_excluded",
      goodWhen: ["云南小吃"],
      avoidWhen: ["要吃大的"],
      vetoRisks: ["小吃感"],
    },
  },
  {
    id: "yu-li-xiang",
    name: "御鲤湘",
    address: "北京西路1135号",
    location: {
      bucket: "city",
      label: "北京西路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步"],
    },
    identity: {
      cuisine: "湘菜",
      cuisineFamilies: ["hunan"],
      preferenceTier: "low",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "hunan_hot",
      heaviness: "heavy",
    },
    dishes: ["双色鱼头", "紫苏爆牛蛙", "长沙臭豆腐"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["湘菜低频", "想吃鱼头牛蛙"],
      avoidWhen: ["想稳妥 top"],
      vetoRisks: ["偏好低"],
    },
  },
  {
    id: "southern-barbarian",
    name: "南蛮子 Southern Barbarian",
    address: "进贤路167号与169号之间M56号大门进入上二楼",
    location: {
      bucket: "city",
      label: "进贤路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步", "冰激凌", "喝酒"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "low",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "yunnan_spicy",
      heaviness: "medium",
    },
    dishes: ["见手青", "包浆豆腐", "黑三剁", "生炸排骨", "老奶洋芋", "乳扇"],
    decision: {
      defaultEligibility: "backup_pool",
      goodWhen: ["云南低频", "进城喝酒散步"],
      avoidWhen: ["想稳妥 top"],
      vetoRisks: ["偏好低"],
    },
  },
  {
    id: "albaluz",
    name: "ALBALUZ 西班牙餐厅",
    address: "天平路320弄衡山坊23号楼",
    location: {
      bucket: "home_route",
      label: "徐家汇衡山坊",
      driveCompany: "中距离",
      driveHome: "顺路",
      transitCompany: "中等",
      transitHome: "顺路",
      detour: "small_detour",
      routeVerdict: "回家顺路",
      afterMealOptions: ["散步"],
    },
    identity: {
      cuisine: "西班牙菜",
      cuisineFamilies: ["western"],
      preferenceTier: "exception",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "none",
      spiceStyle: "not_spicy",
      heaviness: "medium",
    },
    dishes: ["西班牙海鲜饭", "蒜味热橄榄油浸黑虎虾虾仁", "墨汁意面"],
    decision: {
      defaultEligibility: "exception_pool",
      goodWhen: ["没胃口", "回家顺路西餐"],
      avoidWhen: ["不要西餐", "要辣"],
      vetoRisks: ["不辣", "西餐"],
    },
  },
  {
    id: "mithai",
    name: "米泰 MiThai",
    address: "安福路195号2楼",
    location: {
      bucket: "home_route",
      label: "安福路",
      driveCompany: "进城",
      driveHome: "顺路",
      transitCompany: "进城",
      transitHome: "顺路",
      detour: "small_detour",
      routeVerdict: "回家顺路",
      afterMealOptions: ["散步"],
    },
    identity: {
      cuisine: "泰国菜",
      cuisineFamilies: ["thai"],
      preferenceTier: "exception",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "medium",
      spiceStyle: "sour_spicy",
      heaviness: "medium",
    },
    dishes: ["冬阴功", "猪颈肉", "菠萝炒饭"],
    decision: {
      defaultEligibility: "exception_pool",
      goodWhen: ["想酸辣但不要湘滇", "回家顺路"],
      avoidWhen: ["只想云南湘菜", "要很辣"],
      vetoRisks: ["不是湘滇"],
    },
  },
  {
    id: "nepali-kitchen",
    name: "尼泊尔餐厅 Nepali Kitchen",
    address: "巨鹿路819弄4号",
    location: {
      bucket: "city",
      label: "巨鹿路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步", "冰激凌", "喝酒"],
    },
    identity: {
      cuisine: "尼泊尔菜",
      cuisineFamilies: ["nepalese"],
      preferenceTier: "exception",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "none",
      spiceStyle: "not_spicy",
      heaviness: "heavy",
    },
    dishes: ["尼泊尔烤羊排", "黄油馕", "咖喱羊肉"],
    decision: {
      defaultEligibility: "exception_pool",
      goodWhen: ["想不辣大肉", "进城喝酒散步"],
      avoidWhen: ["要辣", "不要西餐类"],
      vetoRisks: ["不辣"],
    },
  },
  {
    id: "yi-zuo-yi-wang",
    name: "一坐一忘云南菜",
    address: "东湖路30幢105室",
    location: {
      bucket: "city",
      label: "东湖路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步"],
    },
    identity: {
      cuisine: "云南菜",
      cuisineFamilies: ["yunnan"],
      preferenceTier: "medium",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "medium",
      spiceStyle: "yunnan_spicy",
      heaviness: "medium",
    },
    dishes: ["腾冲大救驾", "铜锅牛肝菌焖饭", "香茅草烤鲈鱼"],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["云南低频", "避开熟脸 top", "进城散步"],
      avoidWhen: ["一定要跳河那种辣爽"],
      vetoRisks: ["不够辣爽"],
    },
  },
  {
    id: "jiujiu-di-shui-dong",
    name: "久久滴水洞湘菜馆",
    address: "茂名南路56号2楼",
    location: {
      bucket: "city",
      label: "茂名南路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步", "冰激凌", "喝酒"],
    },
    identity: {
      cuisine: "湘菜",
      cuisineFamilies: ["hunan"],
      preferenceTier: "medium",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "hot",
      spiceStyle: "hunan_hot",
      heaviness: "heavy",
    },
    dishes: ["双椒鱼头", "孜然排骨", "干锅牛蛙", "香蕉拔丝", "滴水洞炒饭", "绝味牛蛙锅", "美味猪手"],
    decision: {
      defaultEligibility: "primary_pool",
      goodWhen: ["想吃湘菜但不想锅碗", "进城喝酒散步"],
      avoidWhen: ["重口腻了"],
      vetoRisks: ["重口"],
    },
  },
  {
    id: "alimentari",
    name: "Alimentari Grande",
    address: "东湖路20号101-201室",
    location: {
      bucket: "city",
      label: "东湖路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步", "冰激凌", "喝酒"],
    },
    identity: {
      cuisine: "美国菜",
      cuisineFamilies: ["western"],
      preferenceTier: "exception",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "none",
      spiceStyle: "not_spicy",
      heaviness: "medium",
    },
    dishes: ["披萨", "无花果布拉塔", "鸡蛋牛油果吐司", "开心果冰激凌"],
    decision: {
      defaultEligibility: "exception_pool",
      goodWhen: ["没胃口", "进城西餐例外"],
      avoidWhen: ["不要西餐", "要辣"],
      vetoRisks: ["不辣", "西餐"],
    },
  },
  {
    id: "linghai-yong-zhouji",
    name: "岭海永周记潮州牛肉店",
    address: "进贤路222号",
    location: {
      bucket: "city",
      label: "进贤路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["散步", "冰激凌", "喝酒"],
    },
    identity: {
      cuisine: "潮汕牛肉锅",
      cuisineFamilies: ["chaoshan"],
      preferenceTier: "exception",
      isChain: false,
      mealScale: "big",
      familiar: false,
    },
    taste: {
      spiceLevel: "none",
      spiceStyle: "not_spicy",
      heaviness: "medium",
    },
    dishes: ["吊龙", "匙柄"],
    decision: {
      defaultEligibility: "exception_pool",
      goodWhen: ["不辣但吃大的", "进城散步"],
      avoidWhen: ["要辣", "只想湘滇"],
      vetoRisks: ["不辣"],
    },
  },
  {
    id: "kooriya-shark",
    name: "Kooriya Shark",
    address: "常熟路185号",
    location: {
      bucket: "city",
      label: "常熟路",
      driveCompany: "进城",
      driveHome: "中等",
      transitCompany: "进城",
      transitHome: "中等",
      detour: "medium_detour",
      routeVerdict: "进城顺便逛",
      afterMealOptions: ["甜品"],
    },
    identity: {
      cuisine: "日式刨冰",
      cuisineFamilies: ["dessert"],
      preferenceTier: "exception",
      isChain: false,
      mealScale: "small",
      familiar: false,
    },
    taste: {
      spiceLevel: "none",
      spiceStyle: "not_spicy",
      heaviness: "light",
    },
    dishes: ["草莓刨冰"],
    decision: {
      defaultEligibility: "usually_excluded",
      goodWhen: ["饭后甜品"],
      avoidWhen: ["要吃饭"],
      vetoRisks: ["不是饭"],
    },
  },
];
